spring.application.name=be-u2-s1-g1
# Useremo questo file al posto del persistence
# Qui ci sono tutte le impostazioni che andranno messe per
# impostare il progetto, per esempio connessione ad un DB o ad un Web-server
# Le informazioni in questo file sono messe sotto forma di
# chiave = valore
# per gestire i parametri "application" usa la notazione
# contesto.nomeparametro = valoreparametro
# il contesto fa riferimento all'applicazione od ad una logica di cui si occupa il parametro
# per esempio il nome di una applicazione tipo postgresql
# permette anche di dare lo stesso nome a più parametri che si occupano di app diverse
# in maniera da poterli distinguere
# Aggiungiamo per esempio una admin.name con valore assegnato
admin.name=Gianni
admin.surname=Rossi
#
#
# Per recuperare i valori all'interno del codice si usa
# @Value("${contesto.nomeparametro}")
# inoltre all'interno della classe di configurazione è inoltre necessario
# @PropertySource("application.properties")
